kind = "mobile"
previewPath = "/"
title = "Batter Up"
version = "1.0.0"
id = "artifacts/batter-up"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21078

[services.development]
run = "pnpm --filter @workspace/batter-up run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/batter-up", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/batter-up", "run", "serve" ]

[services.env]
PORT = "21078"
BASE_PATH = "/"
